'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const {Observer}=require('../dist/live-core.js');
const base={status:'running',run:'a',slot:1,stage:1,stageType:0,bridgeVersion:'1.0.1',room:{index:84,listIndex:0,type:1,clear:false},items:[],cards:[],events:[],pickups:[],secretCandidates:[]};
const pickup={id:'a',kind:'heart',subtype:1,price:0,x:20,y:30};
const o=new Observer();
const rocksObserver=new Observer();
const rock={kind:'tinted',index:20,x:100,y:150};
rocksObserver.observe({...base,rocks:[rock]});let rockCount=rocksObserver.entries.length;
rocksObserver.observe({...base,rocks:[rock]});assert.equal(rocksObserver.entries.length,rockCount);
rocksObserver.observe({...base,rocks:[]});assert(rocksObserver.entries.some(e=>e.text.includes('Roccia speciale non più presente')));
o.observe({...base,pickups:[pickup]});let count=o.entries.length;
o.observe({...base,pickups:[{...pickup,x:120,y:80}]});assert.equal(o.entries.length,count,'Movement must not spam the log');
o.observe({...base,pickups:[]});assert.equal(o.entries.filter(e=>e.text.startsWith('Non più presente')).length,1);
o.observe({status:'error'});assert(o.entries.some(e=>e.text.includes('Cuore rosso')),'Error must preserve history');
o.observe(base);assert.equal(o.entries.filter(e=>e.text.includes('Nuova sessione')).length,1);
o.observe({...base,events:[{boss:'Hush',character:'Isaac'}]});
o.observe({...base,events:[{boss:'Hush',character:'Isaac'},{boss:'Mom',character:'Isaac'}]});
assert.equal(o.entries.filter(e=>e.text==='Evento osservato: Hush con Isaac').length,1);
o.observe({...base,stage:2});assert(o.entries.some(e=>e.text.includes('Piano 2')));
o.observe({...base,slot:2});assert(o.entries.some(e=>e.text.includes('slot 2')));
o.clearLog();o.observe({...base,slot:2});assert.equal(o.entries.length,0,'Clear retains observation baseline');
for(let i=0;i<250;i++)o.add('system',String(i));assert.equal(o.entries.length,200);
const t=new Observer();t.observe({...base,pickups:[pickup]});t.observe({...base,pickups:[],pickupsTruncated:true});
assert(!t.entries.some(e=>e.text.startsWith('Non più presente')));
console.log('PASS live observer regression checks.');
