const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.ATLAS_BROWSER?{channel:process.env.ATLAS_BROWSER}:{})});try{
 const p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));let unlocked=[],hash='before';
 await p.route('**/api/sources',r=>r.fulfill({json:{sources:[{id:'fixture',label:'Demo',slots:[1,2,3]}]}}));
 await p.route('**/api/progress?*',r=>r.fulfill({json:{slot:1,version:'Repentance+',unlocked,collected:[],hash,filename:'demo',modified:new Date().toISOString(),checked:new Date().toISOString()}}));
 await p.route('**/api/live',r=>r.fulfill({json:{schema:2,status:'running',slot:1,character:'Tainted Eden',frames:3600,stage:11,difficulty:1,challenge:0,custom:false,players:1,run:'fixture',items:[451],cards:[80],events:[{boss:'Mega Satan',character:'Tainted Eden'}],bossRushLimit:36000,hushLimit:54000}}));
 await p.goto(process.env.ATLAS_URL||'http://127.0.0.1:8768');await p.waitForSelector('.live-task');
 assert.equal(await p.locator('.objective-mark').count(),12);await p.locator('[data-objective="Hush"]').click();assert.equal(await p.locator('#boss').inputValue(),'Hush');assert.equal(await p.locator('[data-objective="Hush"]').getAttribute('aria-pressed'),'true');await p.locator('[data-objective="Hush"]').click();assert.equal(await p.locator('#boss').inputValue(),'');assert((await p.locator('#live-tasks').textContent()).includes('Boss osservati'));assert((await p.locator('#live-timing').textContent()).includes('Boss Rush'));
 unlocked=[610];hash='after';await p.locator('#refresh').click();await p.waitForFunction(()=>document.querySelector('#live-tasks').textContent.includes('Sblocco confermato'));
 await p.locator('#open-planner').click();await p.locator('#plan-character').selectOption('Tainted Eden');assert((await p.locator('#plan-results').textContent()).includes('The Beast'));assert(!(await p.locator('#plan-results').textContent()).includes('Wild Card'));
 await p.locator('#plan-goal').selectOption({label:'Corrupted Data'});assert.equal(await p.locator('.route-plan').count(),1);await p.locator('#plan-goal').selectOption('');
 await p.locator('#search').fill('Spindown Dice');await p.waitForSelector('#results .card');await p.locator('.bookmark').first().click();assert.equal(await p.locator('#saved-count').textContent(),'1');
 await p.locator('#import-pins').setInputFiles({name:'pins.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'isaac-atlas-favourites',version:1,ids:[610]}))});await p.waitForFunction(()=>document.querySelector('#saved-count').textContent==='2');
 await p.locator('#import-pins').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'isaac-atlas-favourites',version:1,ids:[999999]}))});assert.equal(await p.locator('#saved-count').textContent(),'2');await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('non valido'));
 const download=p.waitForEvent('download');await p.locator('#export-pins').click();assert((await download).suggestedFilename().includes('slot-1'));
 await p.locator('#open-settings').click();await p.waitForSelector('#diagnostic-results p');assert(await p.locator('#save-directory').isVisible());await p.locator('#browse-save-directory').click();assert((await p.locator('#settings-feedback').textContent()).includes('browser'));
 // No config or game mutations: mock the only POST used by this UI test.
 await p.route('**/api/bridge/install',r=>r.fulfill({json:{installed:true,message:'Bridge simulata'}}));await p.locator('#install-bridge').click();assert((await p.locator('#settings-feedback').textContent()).includes('Chiudi il gioco'));await p.locator('#game-closed').check();await p.locator('#install-bridge').click();await p.waitForFunction(()=>document.querySelector('#settings-feedback').textContent==='Bridge simulata');await p.locator('#close-settings').click();
 await p.locator('#compact-mode').click();assert(await p.locator('.catalog').isHidden());await p.locator('#compact-mode').click();assert(await p.locator('.catalog').isVisible());
 for(const width of [375,768,1440]){await p.setViewportSize({width,height:1000});const overflow=await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right})));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width+' '+JSON.stringify(overflow));}
 if(process.env.ATLAS_SCREENSHOT){await p.setViewportSize({width:1440,height:1050});await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:process.env.ATLAS_SCREENSHOT});}
 assert.deepEqual(errors,[]);console.log('PASS v1 planner, observed/confirmed events, deadlines, import validation, export, configuration, guided bridge flow, compact mode and responsive layout.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
